name: CI for DoD Spending PDF Search

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]
    
    steps:
    - name: Debug environment before checkout
      run: |
        echo "Runner OS: $RUNNER_OS"
        echo "Git version: $(git --version)"
        echo "Current directory contents:"
        ls -la

    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  
        
    - name: Debug after checkout
      run: |
        echo "Repository contents after checkout:"
        ls -la
        git status

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests googlesearch-python beautifulsoup4 colorama argparse

    - name: Display versions
      run: |
        python --version
        pip --version

    - name: Run default test
      run: python dod_spending.py --output test_output.txt

    - name: Run verbose test
      run: python dod_spending.py -v --output test_output.txt

    - name: Run custom query test
      run: python dod_spending.py -q "Test Search:DoD test filetype:pdf" --output test_output.txt

    - name: Verify output exists
      run: test -f test_output.txt

    - name: Display output
      run: cat test_output.txt

    - name: Archive test output
      uses: actions/upload-artifact@v4
      with:
        name: test-output-${{ matrix.python-version }}
        path: test_output.txt
