name: CI for DoD Spending

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests googlesearch-python beautifulsoup4 colorama argparse

    - name: Display versions
      run: |
        python --version
        pip --version

    - name: Run default test
      run: python dod_spending.py --output test_output.txt

    - name: Run verbose test
      run: python dod_spending.py -v --output test_output.txt

    - name: Run custom query test
      run: python dod_spending.py -q "Test Search:DoD test filetype:pdf" --output test_output.txt

    - name: Verify output exists
      run: test -f test_output.txt

    - name: Display output
      run: cat test_output.txt

    - name: Archive test output
      uses: actions/upload-artifact@v3
      with:
        name: test-output-${{ matrix.python-version }}
        path: test_output.txt
